### ISSUE TITLE
Make OpenMP a conditional compile

### ISSUE THREAD

**Issue by mikeryan** [mikeryan/crackle#15]

**Comment by R1kk3r** [comment]
The cleanest solution would be to use GNU Autoconf to have a configure script shell that will set the flag accordingly to the presence (or not) of libomp library.

**Comment by mikeryan** [comment]
Autoconf is a huge, nasty dep to bring in for such a simple task. I'd like to exhaust all other options before turning to it.

**Comment by mikeryan** [comment]
Ripped out the OpenMP code. Will look into parallelizing using a fork-based model.
