### ISSUE TITLE
Does this still work with BLE 4.2?

### ISSUE THREAD

**Issue by rclai** [mikeryan/crackle#23]
Given the new security implementations that they've done with the ECDH, will this still work?

**Comment by mikeryan** [comment]
This attack does not work with LE Secure Connections from Bluetooth 4.2 that use ECDH key exchange.

If you have any sample devices that actually implement this, I'd love to hear about it!

**Comment by rclai** [comment]
Ah okay cool, thanks. I don't know of any BLE 4.2 devices handy, at least not yet, but when I do it's only going to be a raw BLE module.

**Comment by Simon3** [comment]
Just for information - The new Chromecast with Google TV is using LE Secure Connections / ECDH key exchange!
