### ISSUE TITLE
Decrypted But Cannot View Input Data

### ISSUE THREAD

**Issue by LarryCheech** [mikeryan/crackle#34]
I have captured the entire pairing process and decrypted the capture successfully but I can't view the data entered on the device by the user? 

[decrypted_logitech - full pairing.pcapng.txt](https://github.com/mikeryan/crackle/files/1781764/decrypted_logitech.-.full.pairing.pcapng.txt)

**Comment by mikeryan** [comment]
Load your file in Wireshark and filter using "btatt". The final four displayed packets are "Human Interface Device: Report". These are HID reports that contain whatever keystrokes the user typed. You will need to build some kind of HID decoder to parse these.
