### ISSUE TITLE
Crackle not decrypting the Android BT snooping enabled packet dumps ?

### ISSUE THREAD

**Issue by Kumarasamy** [mikeryan/crackle#37]
Hello ,

I was enabled the bluetooth HCI snoop logs in android device and try to decrypt.  Crackle says  unknown file format .
Is this HCI snoop logs not valid to use crackle?

**Comment by mikeryan** [comment]
HCI snoop logs contain data before link layer encryption is applied. You are looking at unencrypted data.

There could be additional app-layer encryption on top of that, but crackle can't help decrypt that as it's application specific.
