### ISSUE TITLE
Crackle does not work / after instalation Wireshark break down 

### ISSUE THREAD

**Issue by Phase-angle-regulating-transformer** [mikeryan/crackle#39]
Hi Friends

I installed the Crackle from this source: http://lacklustre.net/projects/crackle/ . After installation on Ubuntu, I tried to decrypt BLE packages from PCAP file. When I opened it in Crackle, the Wireshark breaks down and other applications on my computer, like Firefox, too. The crackle destroys the PCAP file, because it is not able to be opened anymore.

**Comment by mikeryan** [comment]
Can you please share the commands you ran?
