### ISSUE TITLE
crackle installation problem

### ISSUE THREAD

**Issue by blakroot** [mikeryan/crackle#42]
**I am not able to install the crackle.** 
`blackroot@blackroot:~/Desktop/crackle-master$ make

cc -O2 -Wall -Werror -g   -c -o crackle.o crackle.c

In file included from crackle.c:38:0:

crackle.h:5:18: fatal error: pcap.h: No such file or directory

compilation terminated.

<builtin>: recipe for target 'crackle.o' failed

make: *** [crackle.o] Error 1
`

**Comment by Catshy** [comment]
maybe you need pcap library.
try:
`sudo apt-get install libpcap-dev
`
