### ISSUE TITLE
decrypt incorrectly

### ISSUE THREAD

**Issue by kydahe** [mikeryan/crackle#48]
I write and compile a ble sm-pairing program on raspberry. And I use a ble debug app on Android to pairing and communicate with it, i.e., read CHARACTERISTIC.
The binding uses Just Works.

Everything goes ok util I try to use Crackle to decrypt captured pcap data.
`crackle -i test.pcap -o output.pcap`

The output is as follow:
`
Found 1 connection

Analyzing connection 0:
  xx:xx:xx:xx:xx:xx  (random) -> xx:xx:xx:xx:xx:xx (public)
  Found 32 encrypted packets
  Cracking with strategy 0, 20 bits of entropy

  !!!
  TK found: 000000
  ding ding ding, using a TK of 0! Just Cracks(tm)
  !!!

  Decrypted 31 packets
  LTK found: 560d2302fe5813b5520295edbadc3909

Decrypted 31 packets, dumping to PCAP
Done, processed 3653 total packets, decrypted 31
`

But the output.pcap seems wrong and all of opertions is not analyzed correctly.
For example, when I read one CHARACTERISTIC, it returns the device name (a const string), but now it was not analyzed correctly.

I open this output.pcap with wireshark, and the error is **"Error Response: Attribute not Found."** and I do not see the device name string in output.pcap.
![image](https://user-images.githubusercontent.com/37690316/102572848-1b73c000-4128-11eb-8a85-3157fadb7f29.png)

Could please help me solve this issues?
Is the Crackle's problem or my program's problem?

Thank you very much.

**Comment by mikeryan** [comment]
Did you capture this data with an Ubertooth? It's likely the Ubertooth didn't capture some of the encrypted packets that contained the device name. The best thing to try is to re-capture the data again and again until you see the data you're looking for.

It's worth checking out the [FAQ entry on whether you need to use crackle or not](https://github.com/mikeryan/crackle/blob/master/FAQ.md#can-i-log-data-without-having-to-sniff).

**Comment by kydahe** [comment]
I tried serveral times but it seems difficult to capture the all packets by Ubertooth.
I will try to find if there are other methods to capture bluetooth data.
Thanks.
