### ISSUE TITLE
decrypting pcapfile

### ISSUE THREAD

**Issue by omarsohail** [mikeryan/crackle#5]
hello mike
I'm trying to run a captured pcap file in crackle which contains all the necessary packets needed to decrypt but it still gives an error and does not detect any packets. any help would be great thanks
![screenshot from 2015-11-20 00 00 31](https://cloud.githubusercontent.com/assets/15115846/11271358/7ba4dc1e-8f19-11e5-8f98-00b84b109fc4.png)

![screenshot from 2015-11-19 23 53 17](https://cloud.githubusercontent.com/assets/15115846/11271308/2e7f9262-8f19-11e5-9efd-9a44c67c7add.png)
![screenshot from 2015-11-19 23 58 30](https://cloud.githubusercontent.com/assets/15115846/11271309/2fb40ba4-8f19-11e5-8b7f-736090eaa9f9.png)

**Comment by mikeryan** [comment]
What command line parameters did you give to ubertooth-btle to capture these packets?

**Comment by omarsohail** [comment]
Ubertooth-btle -f -r /tmp/pcapfile

**Comment by mikeryan** [comment]
Ah, crackle doesn't support that PCAP format (yet). You can either recapture using -c instead of -r, or wait for me to implement it. I plan to bang it out in the next few days.

**Comment by omarsohail** [comment]
Ah I see, in a bit of a tight schedule so I tried using -c as 'ubertooth -f -c /tmp/pipe' or '/tmp/pipe.cap' but it doesn't seem to do anything and takes me back to the command list. thanks for being patient with me as I am still a noob.

**Comment by mikeryan** [comment]
Can you paste the output of ubertooth-btle -h? Also what version of libbtbb and ubertooth are you using? What platform are you on?

**Comment by omarsohail** [comment]
I'm currently using the 2015-09-R2 version on libbtbb and ubertooth one on kali linux 2.0

![screenshot from 2015-11-20 00 00 31](https://cloud.githubusercontent.com/assets/15115846/11289790/1f66c8ca-8f84-11e5-96dd-3880c0e4fa76.png)

**Comment by mikeryan** [comment]
And the output of ubertooth-btle -h?

**Comment by omarsohail** [comment]
sorry wrong image
![screenshot from 2015-11-20 12 43 29](https://cloud.githubusercontent.com/assets/15115846/11289981/3a1f74b2-8f86-11e5-83ea-ac48abe92a68.png)

**Comment by mikeryan** [comment]
It looks like libbtbb was built without PCAP support. Did you build this yourself? If so, can you apt-get install libpcap-dev and rebuild libbtbb and ubertooth (including rerunning cmake in a fresh build dir)?

**Comment by omarsohail** [comment]
hey I have now updated both the firmwares and I am now getting -c but when I'm running ubertooth -f -c tmp/pipe it runs fine but no file is being saved.
![screenshot from 2015-11-20 13 16 53](https://cloud.githubusercontent.com/assets/15115846/11290187/c28363f2-8f88-11e5-807c-78b61494265d.png)

**Comment by mikeryan** [comment]
Does /tmp/pipe exist? Have you tried any different filenames? This is very odd behavior, I've never seen it.

**Comment by omarsohail** [comment]
I managed to get it working, wireshark was being a pain in the ass and wasn't accepting pipe as a interface. -c is working fine now, Thank you very much mike!
also just wanted to ask if there are devices that are best for sniffing and decrypting?

**Comment by mikeryan** [comment]
I'm a big fan of TI's BLE SensorTag. You can use BlueZ to talk to it and enable encryption, which makes it great for doing lots of trial runs.

**Comment by omarsohail** [comment]
hey mike
I got crackle working and captured and entire pairing conversation between a vivosmart activity tracker and an iPhone using -c but crackle still gives me this


![screenshot from 2015-11-20 15 59 30](https://cloud.githubusercontent.com/assets/15115846/11292282/d8cde724-8f9f-11e5-9cc5-278f74b3e142.png)

**Comment by mikeryan** [comment]
That is a common issue: Ubertooth doesn't have a 100% packet capture rate, and it missed some of the important packets. Try re-running the pairing process several times, and you will eventually capture all of the packets. It's fairly labor intensive but it does ultimately work in the long run.

**Comment by JelteF** [comment]
My change in pull request #6 makes this a bit better, since it only needs 1 confirm packet instead of two.

**Comment by mikeryan** [comment]
A ton of stuff has been merged that should improve this. Give that a try, and reopen the issue if you're still having trouble.
