### ISSUE TITLE
document STK brute force (-s) mode

### ISSUE THREAD

**Issue by mikeryan** [mikeryan/crackle#9]
The -h text does not mention it, nor does README

**Comment by JelteF** [comment]
Yeah, that should probably be added.

**Comment by JelteF** [comment]
The `-r` flag is also not honoured btw.

**Comment by mikeryan** [comment]
The ```-r``` flag is for demonstration purposes. I don't think it's strictly necessary for anything else to honor it, and in fact I'd be willing to remove it since it doesn't add any meaningful functionality.

**Comment by mikeryan** [comment]
The freshly pushed code automatically selects STK brute forcing mode (as "strategy 0") when appropriate. I've removed the option from the option parser.
